version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Xp@199866
    volumes:
      - mysqldata:/var/lib/mysql
      - mysqlconf:/etc/mysql/conf.d
      - mysqllog:/var/log/mysql
    ports:
      - 3306:3306
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - backend

  backend:
    build:
      context:.
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/your-jar-file.jar # 这里请根据实际的后端jar包路径修改
    container_name: backend
    volumes:
      - /usr/local/java:/usr/local/java
    ports:
      - 9898:9898
    networks:
      - backend
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - /usr/local/nginx/html:/usr/share/nginx/html
      - /usr/local/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /usr/local/nginx/https:/usr/share/nginx/https
    ports:
      - 80:80
      - 443:443
    networks:
      - backend
    depends_on:
      - backend

volumes:
  mysqldata:
  mysqlconf:
  mysqllog:

networks:
  backend: