spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://182.92.154.131:3306/industrial_ecommerce?characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/industrial_ecommerce?characterEncoding=UTF-8
    username: root
    password: 123456
#    username: root
#    password: Xp@199866
  jackson:
    time-zone: UTC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.qq.com
    username: 3170195273@qq.com
    password: kiajacqmbvqbdgfa
    default-encoding: UTF-8
    port: 465
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
mybatis:
  configuration:
    map-underscore-to-camel-case: true
crawler:
  timeout-ms: 30000
  user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36"
  sources:
    tmall: "https://detail.tmall.com/item.htm?id=%s" # 添加必要参数
  selectors:
    tmall:
      price:
        selector: "div[style*='color: rgb(255, 79, 0)'] > span.text--Mdqy24Ex"
        transform: |
          value.replace(/[^\d.]/g, '')

jwt:
  secret: "5a8f1c3d7e2b9a406d5e8c7b3a0f2d1e4c5b6a7f8d9e0c1b2a3f4e5d6c7b8a" # 替换为实际密钥
  access-token-expiration: 7200000  # 2小时 (毫秒)
  refresh-token-expiration: 604800000  # 7天 (毫秒)
  cookie:
#    domain: yourdomain.com # 根据实际部署环境配置
    secure: true # 生产环境设为true

# 数据加密配置
result:
  encryption:
    enabled: true # 启用响应数据加密
    key: "u/FLkK6b4q7AeD2gHjMpQsVvXyZabcde=" # 有效的 Base64 编码密钥


server:
  port: 8080
  servlet:
    session:
      cookie:
        domain: 182.92.154.131
        same-site: lax
        secure: false

llm:
  endpoint: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
