spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://182.92.154.131:3306/industrial_ecommerce?characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/industrial_ecommerce?characterEncoding=UTF-8
    username: root
    password: 123456
#    username: root
#    password: Xp@199866
  jackson:
    time-zone: UTC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
crawler:
  timeout-ms: 30000
  user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36"
  sources:
    tmall: "https://detail.tmall.com/item.htm?id=%s" # 添加必要参数
  selectors:
    tmall:
      price:
        selector: "div[style*='color: rgb(255, 79, 0)'] > span.text--Mdqy24Ex"
        transform: |
          value.replace(/[^\d.]/g, '')


server:
  port: 8080
  servlet:
    session:
      cookie:
        domain: 182.92.154.131
        same-site: lax
        secure: false
